# Generated by Django 5.0.2 on 2024-02-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKeysModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_name", models.CharField(max_length=1000)),
                ("key_value", models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("videoId", models.CharField(max_length=100, unique=True)),
                ("publishedAt", models.DateTimeField()),
                ("channelId", models.CharField(max_length=100)),
                ("videoTitle", models.CharField(max_length=2500)),
                ("videoDescription", models.CharField(max_length=5000)),
                ("thumbnailUrl", models.CharField(max_length=250)),
                ("channelTitle", models.CharField(max_length=250)),
            ],
        ),
    ]
