# Generated by Django 5.0.2 on 2024-02-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(editable=False, max_length=100, unique=True)),
                ('publishedAt', models.DateTimeField()),
                ('channelId', models.CharField(editable=False, max_length=100, unique=True)),
                ('videoTitle', models.CharField(editable=False, max_length=2500, unique=True)),
                ('videoDescription', models.CharField(editable=False, max_length=5000, unique=True)),
                ('thumbnailUrl', models.CharField(editable=False, max_length=250, unique=True)),
                ('channelTitle', models.CharField(editable=False, max_length=250, unique=True)),
            ],
        ),
    ]
