# Generated by Django 5.0.2 on 2024-02-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodatamodel',
            name='channelTitle',
            field=models.CharField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='videodatamodel',
            name='thumbnailUrl',
            field=models.CharField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='videodatamodel',
            name='videoDescription',
            field=models.CharField(editable=False, max_length=5000),
        ),
        migrations.AlterField(
            model_name='videodatamodel',
            name='videoTitle',
            field=models.CharField(editable=False, max_length=2500),
        ),
    ]
