# Generated by Django 5.0.2 on 2024-02-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_videodatamodel_channeltitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodatamodel',
            name='channelId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videodatamodel',
            name='channelTitle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='videodatamodel',
            name='thumbnailUrl',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='videodatamodel',
            name='videoDescription',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='videodatamodel',
            name='videoId',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videodatamodel',
            name='videoTitle',
            field=models.CharField(max_length=2500),
        ),
    ]
